GET http://localhost:3003/user

###
POST http://localhost:3003/user/add
Content-Type: application/json

{
    "username": "Nanda Renata",
    "email": "dewi@gmail.com",
    "password":"123456"
}

###
PUT http://localhost:3003/user
Content-Type: application/json

{
    "_id": "6141da580ff6ee3a18df9b2b",
    "username": "Dani Maulana update agains",
    "email": "danicraft0017@gmail.com",
    "password": "123456"
}

###
GET http://localhost:3003/user/614161f724026930e8b69e81