GET http://localhost:3003/user

###
POST http://localhost:3003/user/add
Content-Type: application/json

{
    "username": "Firnanda Saputra",
    "email": "antin@gmail.com",
    "password":"123456"
}

###
GET http://localhost:3003/user/613feb53fb5d3f0d78e0859b