GET http://localhost:3003/user

###
POST http://localhost:3003/user/add
Content-Type: application/json

{
    "username": "Nanda Renata",
    "email": "dewi@gmail.com",
    "password":"123456"
}

###
GET http://localhost:3003/user/614161f724026930e8b69e81